import { Palette } from "std-widgets.slint";
import { UPrimaryColor, UAppThemeConfig } from "structs/theme.slint";
import { ULightColors, UDarkColors } from "colors.slint";


export global UAppTheme {
    in-out property <UAppThemeConfig> theme: Palette.color-scheme == ColorScheme.dark ? root.dark : root.light;
    
	// Animation duration
	out property <duration> animation-duration: root.theme.animation-duration;

    // Main colors
    out property <UPrimaryColor> primary: root.theme.primary;
    out property <UPrimaryColor> success: root.theme.success;
    out property <UPrimaryColor> warning: root.theme.warning;
    out property <UPrimaryColor> danger: root.theme.danger;

    // Background colors
    out property <brush> bg-layout: root.theme.bg-layout;
    out property <brush> bg-container: root.theme.bg-container;
    out property <brush> bg-elevated: root.theme.bg-elevated;
    out property <brush> bg-spotlight: root.theme.bg-spotlight;

    // Fill colors
    out property <brush> color-fill-plus: root.theme.color-fill-plus;
    out property <brush> color-fill: root.theme.color-fill;
    out property <brush> color-fill-secondary: root.theme.color-fill-secondary;
    out property <brush> color-fill-tertiary: root.theme.color-fill-tertiary;
    out property <brush> color-fill-quaternary: root.theme.color-fill-quaternary;

    // Borders
    out property <length> border-width-base: root.theme.border-width-base;
    out property <brush> border: root.theme.border;
    out property <brush> border-secondary: root.theme.border-secondary;
    out property <brush> separator: root.theme.separator;

    // Shadow
    out property <brush> shadow-color: root.theme.shadow-color;
    out property <length> shadow-blur: root.theme.shadow-blur;
    out property <length> shadow-x-offset: root.theme.shadow-x-offset;
    out property <length> shadow-y-offset: root.theme.shadow-y-offset;

    // Focus display
    out property <brush> focus-color: root.theme.focus-color;
    out property <length> focus-border-width: root.theme.focus-border-width;

    // Text colors
	// Color used for the text in widgets with a primary color as a background.
	out property <brush> primary-text: root.theme.primary-text;
    out property <brush> inverse-text: root.theme.inverse-text;
    out property <brush> text: root.theme.text;
    out property <brush> text-secondary: root.theme.text-secondary;
    out property <brush> text-tertiary: root.theme.text-tertiary;
    out property <brush> text-quaternary: root.theme.text-quaternary;
    out property <brush> text-disabled: root.theme.text-disabled;

    // Font sizes
    out property <length> font-size-smaller: root.theme.font-size-smaller;
    out property <length> font-size-small: root.theme.font-size-small;
    out property <length> font-size-base: root.theme.font-size-base;
    out property <length> font-size-medium: root.theme.font-size-medium;
    out property <length> font-size-big: root.theme.font-size-big;
    out property <length> font-size-bigger: root.theme.font-size-bigger;
	
    // Icons
    out property <length> icon-size-base: root.theme.icon-size-base;

    // Padding
    out property <length> padding-vertical: root.theme.padding-vertical;
    out property <length> padding-horizontal: root.theme.padding-horizontal;
    out property <length> padding-small: root.theme.padding-small;
    out property <length> padding-base: root.theme.padding-base;
    out property <length> padding-medium: root.theme.padding-medium;
    out property <length> padding-big: root.theme.padding-big;
    out property <length> padding-bigger: root.theme.padding-bigger;

    // Spacing
    out property <length> spacing-small: root.theme.spacing-small;
    out property <length> spacing-base: root.theme.spacing-base;
    out property <length> spacing-medium: root.theme.spacing-medium;
    out property <length> spacing-big: root.theme.spacing-big;
    out property <length> spacing-bigger: root.theme.spacing-bigger;

    // Radius
    out property <length> radius-small: root.theme.radius-small;
    out property <length> radius-base: root.theme.radius-base;
    out property <length> radius-medium: root.theme.radius-medium;
    out property <length> radius-large: root.theme.radius-large;
    out property <length> radius-round: root.theme.radius-round;
    out property <length> radius-circle: root.theme.radius-circle;

	// Theming configurations
    in-out property <UAppThemeConfig> light: {
		// Animation duration
		animation-duration: 150ms,

		// Primary colors
        primary: ULightColors.daybreak-blue,
        success: ULightColors.polar-green,
        warning: ULightColors.calendula-gold,
        danger: ULightColors.dust-red,

		// Background colors
		bg-layout: #F5F5F5,
        bg-container: Colors.white,
        bg-elevated: Colors.white,
        bg-spotlight: #262626,

    	// Fill colors
		color-fill-plus: rgb(192, 192, 192),
        color-fill: rgb(217, 217, 217),
        color-fill-secondary: rgb(240, 240, 240),
        color-fill-tertiary: rgb(245, 245, 245),
        color-fill-quaternary: rgb(250, 250, 250),

    	// Borders
    	border-width-base: 1px,
        border: #D9D9D9,
        border-secondary: #f0f0f0,
        separator: #0505050F,

    	// Shadow
    	shadow-color: rgba(0, 0, 0, 0.12),
        shadow-blur: 16px,
        shadow-x-offset: 0px,
        shadow-y-offset: 6px,

    	// Focus display
    	focus-color: Colors.black,
        focus-border-width: 2px,

    	// Text colors
		// Color used for the text in widgets with a primary color as a background.
		primary-text: #ffffff,
        inverse-text: #FFFFFFD9,
        text: #000000E0,
        text-secondary: #000000A6,
        text-tertiary: #00000073,
        text-quaternary: #00000040,
        text-disabled: #00000040,

    	// Font sizes
    	font-size-smaller: 10px,
        font-size-small: 12px,
        font-size-base: 14px,
        font-size-medium: 16px,
        font-size-big: 18px,
        font-size-bigger: 20px,
	
    	// Icons
    	icon-size-base: 16px,

    	// Padding
    	padding-vertical: 5px,
        padding-horizontal: 14px,
        padding-small: 2px,
        padding-base: 4px,
        padding-medium: 8px,
        padding-big: 12px,
        padding-bigger: 16px,

    	// Spacing
    	spacing-small: 2px,
        spacing-base: 4px,
        spacing-medium: 8px,
        spacing-big: 12px,
        spacing-bigger: 16px,

    	// Radius
    	radius-small: 2px,
        radius-base: 4px,
        radius-medium: 8px,
        radius-large: 12px,
        radius-round: 20px,
        radius-circle: 9999px,
    };
    in-out property <UAppThemeConfig> dark: {
		// Animation duration
		animation-duration: 150ms,

		// Primary colors
        primary: UDarkColors.daybreak-blue,
        success: UDarkColors.polar-green,
        warning: UDarkColors.calendula-gold,
        danger: UDarkColors.dust-red,

		// Background colors
		bg-layout: Colors.black,
        bg-container: #141414,
        bg-elevated: #1f1f1f,
        bg-spotlight: #424242,

    	// Fill colors
		color-fill-plus: rgb(86, 86, 86),
        color-fill: rgb(62, 62, 62),
        color-fill-secondary: rgb(48, 48, 48),
        color-fill-tertiary: rgb(39, 39, 39),
        color-fill-quaternary: rgb(30, 30, 30),

    	// Borders
    	border-width-base: 1px,
        border: #424242,
        border-secondary: #303030,
        separator: #FDFDFD1F,

    	// Shadow
    	shadow-color: rgba(0, 0, 0, 0.12),
        shadow-blur: 16px,
        shadow-x-offset: 0px,
        shadow-y-offset: 6px,

    	// Focus display
    	focus-color: Colors.white,
        focus-border-width: 2px,

    	// Text colors
		// Color used for the text in widgets with a primary color as a background.
		primary-text: #ffffff,
        inverse-text: #000000E0,
        text: #FFFFFFD9,
        text-secondary: #FFFFFFA6,
        text-tertiary: #FFFFFF73,
        text-quaternary: #FFFFFF40,
        text-disabled: #FFFFFF40,

    	// Font sizes
    	font-size-smaller: 10px,
        font-size-small: 12px,
        font-size-base: 14px,
        font-size-medium: 16px,
        font-size-big: 18px,
        font-size-bigger: 20px,
	
    	// Icons
    	icon-size-base: 16px,

    	// Padding
    	padding-vertical: 5px,
        padding-horizontal: 14px,
        padding-small: 2px,
        padding-base: 4px,
        padding-medium: 8px,
        padding-big: 12px,
        padding-bigger: 16px,

    	// Spacing
    	spacing-small: 2px,
        spacing-base: 4px,
        spacing-medium: 8px,
        spacing-big: 12px,
        spacing-bigger: 16px,

    	// Radius
    	radius-small: 2px,
        radius-base: 4px,
        radius-medium: 8px,
        radius-large: 12px,
        radius-round: 20px,
        radius-circle: 9999px,
    };
    out property <UPrimaryColor> dust-red: Palette.color-scheme == ColorScheme.dark ? UDarkColors.dust-red : ULightColors.dust-red;
    out property <UPrimaryColor> volcano: Palette.color-scheme == ColorScheme.dark ? UDarkColors.volcano : ULightColors.volcano;
    out property <UPrimaryColor> sunset-orange: Palette.color-scheme == ColorScheme.dark ? UDarkColors.sunset-orange : ULightColors.sunset-orange;
    out property <UPrimaryColor> calendula-gold: Palette.color-scheme == ColorScheme.dark ? UDarkColors.calendula-gold : ULightColors.calendula-gold;
    out property <UPrimaryColor> sunrise-yellow: Palette.color-scheme == ColorScheme.dark ? UDarkColors.sunrise-yellow : ULightColors.sunrise-yellow;
    out property <UPrimaryColor> lime: Palette.color-scheme == ColorScheme.dark ? UDarkColors.lime : ULightColors.lime;
    out property <UPrimaryColor> polar-green: Palette.color-scheme == ColorScheme.dark ? UDarkColors.polar-green : ULightColors.polar-green;
    out property <UPrimaryColor> cyan: Palette.color-scheme == ColorScheme.dark ? UDarkColors.cyan : ULightColors.cyan;
    out property <UPrimaryColor> daybreak-blue: Palette.color-scheme == ColorScheme.dark ? UDarkColors.daybreak-blue : ULightColors.daybreak-blue;
    out property <UPrimaryColor> geek-blue: Palette.color-scheme == ColorScheme.dark ? UDarkColors.geek-blue : ULightColors.geek-blue;
    out property <UPrimaryColor> golden-purple: Palette.color-scheme == ColorScheme.dark ? UDarkColors.golden-purple : ULightColors.golden-purple;
    out property <UPrimaryColor> french-magenta: Palette.color-scheme == ColorScheme.dark ? UDarkColors.french-magenta : ULightColors.french-magenta;
}
