import { UPrimaryColor } from "structs/theme.slint";


export global ULightColors {
    out property <UPrimaryColor> dust-red: {
        base: #f5222d,
        hover: #ff4d4f,
        active: #cf1322,
        disabled: #ff7875,
        selected: #fff1f0,
    };
    out property <UPrimaryColor> volcano: {
        base: #fa541c,
        hover: #ff7a45,
        active: #d4380d,
        disabled: #ff9c6e,
        selected: #fff2e8,
    };
    out property <UPrimaryColor> sunset-orange: {
        base: #fa8c16,
        hover: #ffa940,
        active: #d46b08,
        disabled: #ffc069,
        selected: #fff7e6,
    };
    out property <UPrimaryColor> calendula-gold: {
        base: #faad14,
        hover: #ffc53d,
        active: #d48806,
        disabled: #ffd666,
        selected: #fffbe6,
    };
    out property <UPrimaryColor> sunrise-yellow: {
        base: #fadb14,
        hover: #ffec3d,
        active: #d4b106,
        disabled: #fff566,
        selected: #feffe6,
    };
    out property <UPrimaryColor> lime: {
        base: #a0d911,
        hover: #bae637,
        active: #7cb305,
        disabled: #d3f261,
        selected: #fcffe6,
    };
    out property <UPrimaryColor> polar-green: {
        base: #52c41a,
        hover: #73d13d,
        active: #389e0d,
        disabled: #95de64,
        selected: #f6ffed,
    };
    out property <UPrimaryColor> cyan: {
        base: #13c2c2,
        hover: #36cfc9,
        active: #08979c,
        disabled: #5cdbd3,
        selected: #e6fffb,
    };
    out property <UPrimaryColor> daybreak-blue: {
        base: #1677ff,
        hover: #4096ff,
        active: #0958d9,
        disabled: #69b1ff,
        selected: #e6f4ff,
    };
    out property <UPrimaryColor> geek-blue: {
        base: #2f54eb,
        hover: #597ef7,
        active: #1d39c4,
        disabled: #85a5ff,
        selected: #f0f5ff,
    };
    out property <UPrimaryColor> golden-purple: {
        base: #722ed1,
        hover: #9254de,
        active: #531dab,
        disabled: #b37feb,
        selected: #f9f0ff,
    };
    out property <UPrimaryColor> french-magenta: {
        base: #eb2f96,
        hover: #f759ab,
        active: #c41d7f,
        disabled: #ff85c0,
        selected: #fff0f6,
    };
}

export global UDarkColors {
    out property <UPrimaryColor> dust-red: {
        base: #d32029,
        hover: #e84749,
        active: #a61d24,
        disabled: #791a1f,
        selected: #431418,
    };
    out property <UPrimaryColor> volcano: {
        base: #d84a1b,
        hover: #e87040,
        active: #aa3e19,
        disabled: #7c3118,
        selected: #441d12,
    };
    out property <UPrimaryColor> sunset-orange: {
        base: #d87a16,
        hover: #e89a3c,
        active: #aa6215,
        disabled: #7c4a15,
        selected: #442a11,
    };
    out property <UPrimaryColor> lime: {
        base: #8bbb11,
        hover: #a9d134,
        active: #6f9412,
        disabled: #536d13,
        selected: #2e3c10,
    };
    out property <UPrimaryColor> calendula-gold: {
        base: #d89614,
        hover: #e8b339,
        active: #aa7714,
        disabled: #7c5914,
        selected: #443111,
    };
    out property <UPrimaryColor> sunrise-yellow: {
        base: #d8bd14,
        hover: #e8d639,
        active: #aa9514,
        disabled: #7c6e14,
        selected: #443b11,
    };
    out property <UPrimaryColor> polar-green: {
        base: #49aa19,
        hover: #6abe39,
        active: #3c8618,
        disabled: #306317,
        selected: #1d3712,
    };
    out property <UPrimaryColor> cyan: {
        base: #13a8a8,
        hover: #33bcb7,
        active: #138585,
        disabled: #146262,
        selected: #113536,
    };
    out property <UPrimaryColor> daybreak-blue: {
        base: #1668dc,
        hover: #3c89e8,
        active: #1554ad,
        disabled: #15417e,
        selected: #112545,
    };
    out property <UPrimaryColor> geek-blue: {
        base: #2b4acb,
        hover: #5273e0,
        active: #263ea0,
        disabled: #203175,
        selected: #161d40,
    };
    out property <UPrimaryColor> golden-purple: {
        base: #642ab5,
        hover: #854eca,
        active: #51258f,
        disabled: #3e2069,
        selected: #24163a,
    };
    out property <UPrimaryColor> french-magenta: {
        base: #cb2b83,
        hover: #e0529c,
        active: #a02669,
        disabled: #75204f,
        selected: #40162f,
    };
}
