import { UAppTheme } from "../../app-theme.slint";

import { UText } from "../text.slint";
import { ButtonInterface } from "../button-interface.slint";

import {
    UMenuLogic,
    UMenuVariant,
    UMenuLinkTheme,
    UMenuLinkThemes,
} from "index.slint";


export component UMenuLink inherits Rectangle {
    private property <UMenuLinkTheme> theme: {
        if UMenuLogic.variant == UMenuVariant.light {
            return UMenuLinkThemes.light;
        } else if UMenuLogic.variant == UMenuVariant.dark {
            return UMenuLinkThemes.dark;
        }
        return UMenuLinkThemes.default;
    };
    in-out property <string> id;
    in-out property <string> name;
    in-out property <bool> enabled: true;
    out property <bool> is-selected: UMenuLogic.current-link == id;
    in-out property <int> parent-child-opened;
    init => {
        if is-selected {
            parent-child-opened += 1;
        }
    }
    changed is-selected => {
        parent-child-opened += is-selected ? 1 : -1;
    }
    callback activated();
    ButtonInterface {
        animate background { duration: 0; }
        enabled: root.enabled;
        clicked => {
            if UMenuLogic.current-link != id {
                UMenuLogic.current-link = id;
                root.activated();
            }
        }
        border-radius: UAppTheme.radius-base;
        HorizontalLayout {
            alignment: space-between;
            padding: UAppTheme.padding-base;
            padding-top: UAppTheme.padding-vertical;
            padding-bottom: UAppTheme.padding-vertical;
            padding-left: UAppTheme.padding-horizontal;
            padding-right: UAppTheme.padding-horizontal;
            link-text := UText {
                text: name;
                overflow: elide;
                color: theme.text;
            }
        }

        states [
            disabled when !root.enabled: {
                link-text.color: theme.text-disabled;
            }
            focus-selected when self.has-tab-focus && root.is-selected: {
                background: theme.bg-selected;
                link-text.color: theme.text-selected;
                border-color: UAppTheme.focus-color;
                border-width: UAppTheme.focus-border-width;
            }
            selected when root.is-selected: {
                background: theme.bg-selected;
                link-text.color: theme.text-selected;
            }
            focus-hover when self.has-tab-focus && self.has-hover: {
                border-color: UAppTheme.focus-color;
                border-width: UAppTheme.focus-border-width;
                background: theme.bg-hover;
            }
            hover when self.has-hover: {
                background: theme.bg-hover;
            }
            focus when self.has-tab-focus: {
                border-color: UAppTheme.focus-color;
                border-width: UAppTheme.focus-border-width;
            }
        ]
    }
}
