import { Palette } from "std-widgets.slint";

import { UAppTheme } from "../../app-theme.slint";

import { UMenuLogic, UMenuVariant } from "index.slint";
import { UMenuLink } from "menu-link.slint";
import { UMenuSubmenu } from "menu-submenu.slint";
import { UMenuGroupTitle } from "menu-group-title.slint";


export { UMenuVariant, UMenuLink, UMenuGroupTitle, UMenuSubmenu, UMenuLogic }

export component UMenu inherits Rectangle {
    in-out property <UMenuVariant> variant: default;
    in-out property <string> current-link;
    init => {
        UMenuLogic.variant = variant;
        UMenuLogic.current-link = current-link;
    }
    changed variant => {
        UMenuLogic.variant = variant;
    }
    background: {
        if UMenuLogic.variant == UMenuVariant.light {
            return UAppTheme.light.bg-container;
        } else if UMenuLogic.variant == UMenuVariant.dark {
            return UAppTheme.dark.bg-container;
        }
        return UAppTheme.bg-container;
    };
    VerticalLayout {
        alignment: start;
        @children
    }
}
