// 定义组件和布局
import { TextEdit } from "std-widgets.slint";
import "AlimamaShuHeiTi-Bold.ttf";

export component App inherits Window {
    // 属性：存储计数状态
    in-out property<int> counter: 0;

    // 定义回调
    callback text_changed(string);
    width: 400px;
    height: 300px;
    // 显式指定中文字体，避免中文显示乱码
    // default-font-family: "Hiragino Sans GB";
    // UI布局：垂直排列
    VerticalLayout {
        alignment: LayoutAlignment.center;
        Text {
            // 绑定属性：显示计数
            text: "Count: 你好 \n世界" + counter;
            font-size: 24px;
        }
        TextEdit {
        font-size: 14px;
        width: parent.width;
        height: parent.height;
        text: "Slint 是一个工具，它提供了一种易于学习和使用的语言，用于描述用户界面。这种语言对人类和机器都是可读的。在Slint这种模式下，一方面，我们拥有优秀的工具。 另一方面，能让设计师和开发者通过阅读他们的机器用来显示用户界面的代码，确切地知道发生了什么。";
        edited => {
                root.text_changed(self.text);
            }
    }
    }
}
