// 定义组件和布局
import { TextEdit } from "std-widgets.slint";

export component MainWindow inherits Window {
    // 属性：存储计数状态
    in-out property<int> counter: 0;

    // 定义回调
    callback text_changed(string);
width: 400px;
height: 300px;
    // UI布局：垂直排列
    VerticalLayout {
        alignment: LayoutAlignment.center;
        Text {
            // 绑定属性：显示计数
            text: "Count: 你好 \n世界" + counter;
            font-size: 24px;
        }
        TextEdit {
        font-size: 14px;
        width: parent.width;
        height: parent.height;
        text: "Lorem ipsum dolor sit amet,\n consectetur adipisici elit";
        edited => {
                root.text_changed(self.text);
            }
    }
       
    }
}
