import { UAppTheme } from "../app-theme.slint";
import { ButtonInterface } from "button-interface.slint";

import { UIcon } from "icon.slint";
import { UText } from "text.slint";


export component UCollapse inherits ButtonInterface {
	// Accessability properties
	accessible-role: button;
    accessible-label: self.title;
    accessible-description: @tr("A collapse hiding widgets when closed and showing them when opened.");
    accessible-expandable: true;
    accessible-expanded: self.collapse-open;
    accessible-action-default => {
        self.clicked()
    }
	// Regular properties
    in-out property <string> title <=> collapse-title.text;
    in-out property <bool> collapse-open: false;
    in-out property <length> content-height: collapse-content.preferred-height;
    clicked => {
        collapse-open = !collapse-open;
    }
    VerticalLayout {
        alignment: start;
        HorizontalLayout {
            alignment: start;
            spacing: UAppTheme.spacing-base;
            UIcon {
                size: 20px;
                colorize: UAppTheme.primary.base;
                source: @image-url("../assets/icons/chevron-down.svg");
                transform-rotation: root.collapse-open ? 180deg : 0deg;
                animate transform-rotation { duration: UAppTheme.animation-duration; }
            }

            VerticalLayout {
                alignment: center;
                collapse-title := UText {
                    color: UAppTheme.primary.base;
                    font-size: UAppTheme.font-size-base;
                    accessible-label: @tr("Title for the collapse");
                }
            }
        }

        collapse-content := Rectangle {
            clip: true;
            height: root.collapse-open ? root.content-height : 0px;
            animate height { duration: UAppTheme.animation-duration; }
            @children
        }
    }

    states [
        focused when root.has-tab-focus: {
            border-color: UAppTheme.focus-color;
            border-width: UAppTheme.focus-border-width;
        }
    ]
}
