import { UAppTheme } from "../app-theme.slint";

import { UCard } from "card.slint";
import { UDivider } from "divider.slint";
import { UButton, UButtonVariant } from "button/button.slint";
import { UIconButton, UIconButtonVariant } from "icon-button/icon-button.slint";
import { UTitle } from "title.slint";

export global UModalLogic {
    out property <string> current-id;
    out property <bool> show-modal;
    public function open-modal(id: string) {
        self.current-id = id;
        self.show-modal = true;
    }
    public function close-modal() {
        self.show-modal = false;
    }
}

export component UModal {
    private property <bool> is-opened: id == UModalLogic.current-id && UModalLogic.show-modal;
	// Regular properties
	in-out property <string> id;
    in-out property <string> title;
    in-out property <bool> top-divider: false;
    in-out property <bool> bottom-divider: false;
    in-out property <bool> close-on-click-outside: false;
    in-out property <bool> close-on-accept: true;
    in-out property <bool> close-on-cancel: true;
    in-out property <length> modal-min-width: 300px;
    in-out property <length> modal-min-height;
    in-out property <length> modal-max-width: 600px;
    in-out property <length> modal-max-height: 600px;
    // Bottom buttons properties.
	in-out property <UButtonVariant> accept-btn-variant: primary;
    in-out property <UButtonVariant> cancel-btn-variant: default;
    in-out property <string> accept-btn-text: @tr("Done");
    in-out property <string> cancel-btn-text: @tr("Cancel");
    in-out property <bool> accept-btn-danger: false;
    in-out property <bool> cancel-btn-danger: false;
    in-out property <bool> accept-btn-toggle: true;
    in-out property <bool> cancel-btn-toggle: true;
    in-out property <bool> accept-btn-enabled: true;
    in-out property <bool> cancel-btn-enabled: true;
    callback showed();
    callback closed();
    // Both callbacks are linked to the Cancel/No and Accept/Done/Ok buttons.
	callback accepted();
    callback rejected();
    changed is-opened => {
        if is-opened {
            self.visible = true;
            rect-background-focus.focus();
            self.showed();
        } else {
            self.visible = false;
            self.closed();
        }
    }
    visible: false;
    width: 100%;
    height: 100%;
    Rectangle {
        width: 100%;
        height: 100%;
        background: UAppTheme.color-fill-plus.with-alpha(0.5);

        // Used to skip focus directly to the modal.
		// This avoid having to focus all the elements in the window before getting to the modal.
		rect-background-focus := FocusScope { }

        touch-background := TouchArea {
            clicked => {
                debug("testeing");
                if root.close-on-click-outside {
                    UModalLogic.close-modal();
                }
            }
        }
    }

    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            alignment: center;
            modal-card := UCard {
                min-width: modal-min-width;
                min-height: modal-min-height;
                max-width: modal-max-width;
                max-height: modal-max-height;

                // Used to prevent clicks made in the modal to count as clicks made in the background.
                TouchArea { }

                VerticalLayout {
                    HorizontalLayout {
                        padding-top: UAppTheme.padding-medium;
                        padding-bottom: UAppTheme.padding-medium;
                        padding-left: UAppTheme.padding-big;
                        padding-right: UAppTheme.padding-big;
                        VerticalLayout {
                            alignment: center;
                            UTitle {
                                horizontal-stretch: 1;
                                level: 5;
                                font-weight: 600;
                                text: title;
                                wrap: no-wrap;
                                overflow: elide;
                            }
                        }

                        VerticalLayout {
                            alignment: center;
                            UIconButton {
                                variant: text;
                                icon: @image-url("../assets/icons/x.svg");
                                clicked => {
                                    UModalLogic.close-modal();
                                }
                                accessible-label: @tr("Close the modal.");
                            }
                        }
                    }

                    if top-divider: UDivider { }
                    VerticalLayout {
                        vertical-stretch: 2;
                        padding-top: UAppTheme.padding-medium;
                        padding-bottom: UAppTheme.padding-medium;
                        padding-left: UAppTheme.padding-big;
                        padding-right: UAppTheme.padding-big;
                        @children
                    }

                    if cancel-btn-enabled || accept-btn-enabled: VerticalLayout {
                        alignment: start;
                        vertical-stretch: 0;
                        if bottom-divider: UDivider { }
                        HorizontalLayout {
                            alignment: end;
                            padding-top: UAppTheme.padding-medium;
                            padding-bottom: UAppTheme.padding-medium;
                            padding-left: UAppTheme.padding-big;
                            padding-right: UAppTheme.padding-big;
                            spacing: UAppTheme.spacing-medium;
                            if cancel-btn-toggle: UButton {
                                variant: cancel-btn-variant;
                                text: cancel-btn-text;
                                danger: cancel-btn-danger;
                                enabled: cancel-btn-enabled;
                                clicked => {
                                    self.loading = true;
                                    root.rejected();
                                    self.loading = false;
                                    if close-on-cancel {
                                        UModalLogic.close-modal();
                                    }
                                }
                            }
                            if accept-btn-toggle: UButton {
                                variant: accept-btn-variant;
                                text: accept-btn-text;
                                danger: accept-btn-danger;
                                enabled: accept-btn-enabled;
                                clicked => {
                                    self.loading = true;
                                    root.accepted();
                                    self.loading = false;
                                    if close-on-accept {
                                        UModalLogic.close-modal();
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
