import { UAppTheme } from "../app-theme.slint";
import { ButtonInterface } from "button-interface.slint";

import { UIcon } from "icon.slint";
import { UText } from "text.slint";
import { UIconButton, UIconButtonVariant } from "icon-button/icon-button.slint";


export enum UNotificationVariant {
	info,
	success,
	warning,
	danger,
}

export component UNotification inherits Rectangle {
    in-out property <UNotificationVariant> variant: info;
    in-out property <string> title;
    in-out property <string> message;
    in-out property <bool> single-line-message: true;
    in-out property <image> icon;
    in-out property <brush> icon-color;
    callback close <=> close-button.clicked;
    callback clicked <=> btn-interface.clicked;
    width: 300px;
    background: UAppTheme.bg-elevated;
    border-radius: clamp(UAppTheme.radius-base, 0, 4px);
    border-width: btn-interface.has-tab-focus ? UAppTheme.focus-border-width : 0;
    border-color: btn-interface.has-tab-focus ? UAppTheme.focus-color : transparent;
    drop-shadow-blur: UAppTheme.shadow-blur;
    drop-shadow-color: UAppTheme.shadow-color;
    drop-shadow-offset-y: UAppTheme.shadow-y-offset;
    btn-interface := ButtonInterface {
        VerticalLayout {
            padding: UAppTheme.padding-base;
            HorizontalLayout {
                padding-top: UAppTheme.padding-medium;
                padding-bottom: UAppTheme.padding-medium;
                padding-left: UAppTheme.padding-big;
                padding-right: UAppTheme.padding-big;
                VerticalLayout {
                    alignment: center;
                    padding-right: UAppTheme.padding-medium;
                    UIcon {
                        source: icon;
                        colorize: icon-color;
                        size: UAppTheme.font-size-big;
                        accessible-role: none;
                    }
                }

                VerticalLayout {
                    alignment: center;
                    horizontal-stretch: 1;
                    UText {
                        text: title;
                        wrap: no-wrap;
                        overflow: elide;
                        font-size: UAppTheme.font-size-medium;
                    }
                }

                VerticalLayout {
                    alignment: center;
                    close-button := UIconButton {
                        variant: text;
                        icon: @image-url("../assets/icons/x.svg");
                        accessible-label: @tr("Close notification");
                        accessible-action-default => {
                            self.clicked();
                        }
                    }
                }
            }

            if message != "": HorizontalLayout {
                padding-bottom: UAppTheme.padding-medium;
                padding-left: UAppTheme.font-size-big + UAppTheme.font-size-medium + UAppTheme.padding-base;
                padding-right: UAppTheme.padding-big;
                alignment: start;
                UText {
                    overflow: root.single-line-message ? elide : clip;
                    wrap: root.single-line-message ? no-wrap : word-wrap;
                    text: root.message;
                }
            }
        }
    }

    states [
        info when variant == UNotificationVariant.info: {
            icon: @image-url("../assets/icons/circle-check.svg");
            icon-color: UAppTheme.primary.base;
        }
        success when variant == UNotificationVariant.success: {
            icon: @image-url("../assets/icons/circle-check.svg");
            icon-color: UAppTheme.success.base;
        }
        warning when variant == UNotificationVariant.warning: {
            icon: @image-url("../assets/icons/circle-check.svg");
            icon-color: UAppTheme.warning.base;
        }
        danger when variant == UNotificationVariant.danger: {
            icon: @image-url("../assets/icons/circle-check.svg");
            icon-color: UAppTheme.danger.base;
        }
    ]
}
