import { UAppTheme } from "../app-theme.slint";
import { ButtonInterface } from "button-interface.slint";
import { UText } from "text.slint";
import { UOptionData } from "../structs/data-structs.slint";


component URadioOption inherits ButtonInterface {
	// Accessability properties
	accessible-role: radio-button;
    accessible-label: self.option.text;
    accessible-item-selectable: true;
    accessible-item-selected: is-selected;
    accessible-action-default => {
        self.clicked();
    }
	// Regular properties
    in-out property <UOptionData> option;
    in-out property <string> selected-value;
    private property <bool> is-selected: selected-value == option.value;
    callback selected(value: string);
    clicked => {
        self.selected-value = self.option.value;
        selected(self.option.value);
    }
    HorizontalLayout {
        alignment: start;
        spacing: UAppTheme.spacing-base;
        VerticalLayout {
            alignment: center;
            Rectangle {
                width: UAppTheme.font-size-base;
                height: UAppTheme.font-size-base;
                background: UAppTheme.bg-elevated;
                border-width: UAppTheme.border-width-base;
                border-radius: UAppTheme.radius-circle;
                border-color: UAppTheme.border;
                animate background, border-color { duration: UAppTheme.animation-duration; }
                HorizontalLayout {
                    alignment: center;
                    VerticalLayout {
                        alignment: center;
                        Rectangle {
                            opacity: root.is-selected ? 1 : 0;
                            width: UAppTheme.font-size-base / 3;
                            height: UAppTheme.font-size-base / 3;
                            background: white;
                            border-radius: UAppTheme.radius-circle;
                            animate opacity { duration: UAppTheme.animation-duration; }
                            states [
                                disabled when !root.enabled: {
                                    background: white.with-alpha(0.8);
                                }
                            ]
                        }
                    }
                }

                states [
                    disabled-unselected when !root.enabled && !root.is-selected: {
                        border-color: UAppTheme.border;
                        background: UAppTheme.color-fill-tertiary;
                    }
                    disabled-selected when !root.enabled && root.is-selected: {
                        border-color: UAppTheme.primary.disabled;
                        background: UAppTheme.primary.disabled;
                    }
                    focused-hover-selected when root.has-tab-focus && root.is-selected && root.has-hover: {
                        border-color: UAppTheme.focus-color;
                        border-width: UAppTheme.focus-border-width;
                        background: UAppTheme.primary.hover;
                    }
                    focused-selected when root.has-tab-focus && root.is-selected: {
                        border-color: UAppTheme.focus-color;
                        border-width: UAppTheme.focus-border-width;
                        background: UAppTheme.primary.base;
                    }
                    focused when root.has-tab-focus: {
                        border-color: UAppTheme.focus-color;
                        border-width: UAppTheme.focus-border-width;
                    }
                    hover-unselected when root.has-hover && !root.is-selected: {
                        border-color: UAppTheme.primary.hover;
                    }
                    hover-selected when root.has-hover && root.is-selected: {
                        border-color: UAppTheme.primary.hover;
                        background: UAppTheme.primary.hover;
                    }
                    selected when root.is-selected: {
                        border-color: UAppTheme.primary.base;
                        background: UAppTheme.primary.base;
                    }
                ]
            }
        }

        VerticalLayout {
            alignment: center;
            UText {
                text: root.option.text;
                color: UAppTheme.text;
                font-size: UAppTheme.font-size-base;
                animate color { duration: UAppTheme.animation-duration; }
                states [
                    disabled when !root.enabled: {
                        color: UAppTheme.text-disabled;
                    }
                ]
            }
        }
    }
}

export component URadio {
    accessible-role: groupbox;
    accessible-item-count: self.options.length;
	// Regular properties
	in-out property <bool> enabled: true;
    in-out property <[UOptionData]> options;
    in-out property <string> selected-value;
    in-out property <Orientation> orientation: vertical;
    callback selected(value: string);
    VerticalLayout {
        if orientation == Orientation.vertical: VerticalLayout {
            alignment: start;
            spacing: UAppTheme.spacing-base;
            for option in root.options: URadioOption {
                enabled: root.enabled && option.enabled;
                option: option;
                selected-value <=> root.selected-value;
                selected(value) => {
                    root.selected(value);
                }
            }
        }
        if orientation == Orientation.horizontal: HorizontalLayout {
            alignment: start;
            spacing: UAppTheme.spacing-base;
            for option in root.options: URadioOption {
                enabled: root.enabled && option.enabled;
                option: option;
                selected-value <=> root.selected-value;
                selected(value) => {
                    root.selected(value);
                }
            }
        }
    }
}
