import { UAppTheme } from "../app-theme.slint";
import { ButtonInterface } from "button-interface.slint";


export component USlider inherits ButtonInterface {
	// Accessability properties
	accessible-role: slider;
    accessible-value: root.value;
    accessible-value-step: root.step;
    accessible-value-minimum: root.min-value;
    accessible-value-maximum: root.max-value;
    accessible-action-set-value(value) => {
        if value.is-float() {
            root.value = value.to-float();
        }
    }
    accessible-action-decrement => {
        root.value -= root.step
    }
    accessible-action-increment => {
        root.value += root.step
    }
	// Regular properties
    in-out property <float> value: 0;
    in-out property <float> step: 1;
    in-out property <float> min-value: 0;
    in-out property <float> max-value: 100;
    in-out property <bool> display-steps: false;
    in-out property <Orientation> orientation: horizontal;
    out property <length> handle-pos: ((value - min-value) / (max-value - min-value)) * (is-horizontal ? root.width : root.height);
    private property <length> base-handle-size: 14px;
    private property <bool> is-horizontal: orientation == Orientation.horizontal;
    private property <int> number-of-steps: abs(min-value - max-value) / step;
    changed value => {
        value = clamp(root.value, min-value, max-value);
    }
    function update-value() {
        let pos-value = is-horizontal ? root.mouse-x : (root.height - root.mouse-y);
        let max-length = is-horizontal ? root.width : root.height;
        let raw-value = min-value + (max-value - min-value) * (pos-value / max-length);
        let next-step-up = ceil(raw-value / step) * step;
        let next-step-down = floor(raw-value / step) * step;
        if (raw-value >= value && raw-value >= next-step-up - (step / 2)) {
            value = next-step-up;
        } else if (raw-value < value && raw-value <= next-step-down + (step / 2)) {
            value = next-step-down;
        }
    }
    callback released(value: float);
    changed pressed => {
        if !root.pressed {
            root.released(root.value)
        }
    }
    clicked => {
        update-value();
    }
    moved => {
        update-value();
    }
    key-pressed(event) => {
        if event.text == Key.UpArrow {
            value = max-value;
            return EventResult.accept;
        } else if event.text == Key.DownArrow {
            value = min-value;
            return EventResult.accept;
        } else if event.text == Key.RightArrow {
            value += step;
            return EventResult.accept;
        } else if event.text == Key.LeftArrow {
            value -= step;
            return EventResult.accept;
        }
        return EventResult.reject;
    }
    width: 14px;
    height: 14px;
    if is-horizontal: Rectangle {
        background: UAppTheme.color-fill-secondary;
        border-radius: UAppTheme.radius-circle;
        height: 5px;
        if display-steps: Rectangle {
            private property <length> step-spacing: parent.width / number-of-steps;
            for i in number-of-steps: Rectangle {
                x: i * step-spacing - self.width / 2;
                width: 5px;
                background: self.x > 0 ? UAppTheme.color-fill : transparent;
                border-radius: UAppTheme.radius-round;
            }
        }
        HorizontalLayout {
            alignment: start;
            h-slider := Rectangle {
                background: UAppTheme.primary.base;
                border-radius: UAppTheme.radius-circle;
                width: handle-pos;
                animate background { duration: UAppTheme.animation-duration; }
                states [
                    disabled when !root.enabled: {
                        background: UAppTheme.color-fill;
                    }
                    focus when root.has-tab-focus: {
                        background: UAppTheme.primary.hover;
                    }
                    hover when root.has-hover: {
                        background: UAppTheme.primary.hover;
                    }
                ]
            }
        }

        // Manage the aura-like border that appears around the handle.
        Rectangle {
            private property <length> size: base-handle-size;
            x: h-slider.width - size / 2;
            border-radius: UAppTheme.radius-circle;
            width: size;
            height: size;
            animate size { duration: UAppTheme.animation-duration; }
            states [
                hover when root.enabled && (root.has-hover || root.has-tab-focus): {
                    background: UAppTheme.primary.base.with-alpha(0.2);
                    size: 22px;
                }
            ]
        }

        // The handle itself.
        Rectangle {
            private property <length> size: base-handle-size;
            x: h-slider.width - size / 2;
            background: UAppTheme.bg-container;
            border-color: UAppTheme.primary.base;
            border-width: 2px;
            border-radius: UAppTheme.radius-circle;
            width: size;
            height: size;
            animate border-color, size { duration: UAppTheme.animation-duration; }
            states [
                disabled when !root.enabled: {
                    border-color: UAppTheme.color-fill-plus;
                }
                hover when root.has-hover || root.has-tab-focus: {
                    border-color: UAppTheme.primary.hover;
                    size: 18px;
                }
            ]
        }
    }
    if !is-horizontal: Rectangle {
        background: UAppTheme.color-fill-secondary;
        border-radius: UAppTheme.radius-circle;
        width: 5px;
        if display-steps:Rectangle {
            private property <length> step-spacing: parent.height / number-of-steps;
            for i in number-of-steps: Rectangle {
                y: i * step-spacing - self.height / 2;
                height: 5px;
                background: self.y > 0 ? UAppTheme.color-fill : transparent;
                border-radius: UAppTheme.radius-round;
            }
        }
        VerticalLayout {
            alignment: end;
            v-slider := Rectangle {
                background: UAppTheme.primary.base;
                border-radius: UAppTheme.radius-circle;
                height: handle-pos;
                animate background { duration: UAppTheme.animation-duration; }
                states [
                    disabled when !root.enabled: {
                        background: UAppTheme.color-fill;
                    }
                    focus when root.has-tab-focus: {
                        background: UAppTheme.primary.hover;
                    }
                    hover when root.has-hover: {
                        background: UAppTheme.primary.hover;
                    }
                ]
            }
        }

        // Manage the aura-like border that appears around the handle.
        Rectangle {
            private property <length> size: base-handle-size;
            y: root.height - (v-slider.height + size / 2);
            border-radius: UAppTheme.radius-circle;
            width: size;
            height: size;
            animate size { duration: UAppTheme.animation-duration; }
            states [
                hover when root.has-hover || root.has-tab-focus: {
                    background: UAppTheme.primary.base.with-alpha(0.2);
                    size: 22px;
                }
            ]
        }

        // The handle itself.
        Rectangle {
            private property <length> size: base-handle-size;
            y: root.height - (v-slider.height + size / 2);
            background: UAppTheme.bg-container;
            border-color: UAppTheme.primary.base;
            border-width: 2px;
            border-radius: UAppTheme.radius-circle;
            width: size;
            height: size;
            animate border-color, size { duration: UAppTheme.animation-duration; }
            states [
                disabled when !root.enabled: {
                    border-color: UAppTheme.color-fill-plus;
                }
                hover when root.has-hover || root.has-tab-focus: {
                    border-color: UAppTheme.primary.hover;
                    size: 18px;
                }
            ]
        }
    }
    states [
        focus when root.has-tab-focus: {
            border-color: UAppTheme.focus-color;
            border-width: UAppTheme.focus-border-width;
        }
    ]
}
