import { UAppTheme } from "../app-theme.slint";


export component USpinner inherits Path {
    in-out property <length> size: UAppTheme.icon-size-base;
    in-out property <brush> colorize: UAppTheme.primary.base;
    private property <float> radius: min(self.viewbox-width, self.viewbox-height) / 2;
    private property <float> start-x: self.viewbox-width / 2;
    private property <float> start-y: self.viewbox-height / 2;
    private property <float> start: 0;
    private property <float> progress: 0.8;
    transform-rotation: 240deg * animation-tick() / 1s;
	// Used to apply the transform rotation, otherwise the "transform-rotation" warning will be fired and it won't be applied.
    animate transform-rotation { }
    viewbox-width: 100;
    viewbox-height: 100;
    width: size;
    height: size;
    stroke: colorize;
    stroke-width: 1.5px * size / UAppTheme.icon-size-base;
    stroke-line-cap: round;
    MoveTo {
        x: start-x - radius * sin(-(root.start - 0.001) * 360deg);
        y: start-y - radius * cos(-(root.start - 0.001) * 360deg);
    }

	// Workaround for femtovg not filling complete circle
	LineTo {
        x: start-x - radius * sin(-root.start * 360deg);
        y: start-y - radius * cos(-root.start * 360deg);
    }

    ArcTo {
        radius-x: root.radius;
        radius-y: root.radius;
        x: start-x - root.radius * sin(-290deg);
        y: start-y - root.radius * cos(-290deg);
        sweep: true;
        large-arc: true;
    }
}
