import { UAppTheme } from "../app-theme.slint";
import { ButtonInterface } from "button-interface.slint";


export component USwitch inherits ButtonInterface {
	// Accessability properties
	accessible-role: switch;
    accessible-checkable: true;
    accessible-checked: true;
    accessible-action-default => {
        self.clicked();
    }
	// Regular properties
    in-out property <bool> checked: true;
    background: checked ? UAppTheme.primary.base : UAppTheme.color-fill;
    width: 40px;
    height: 40px / 2;
    border-radius: UAppTheme.radius-round;
    border-width: root.has-tab-focus ? UAppTheme.focus-border-width : 0;
    border-color: root.has-tab-focus ? UAppTheme.focus-color : transparent;
    circle := Rectangle {
        x: checked ? root.height + 2px : 2px;
        width: root.height - 4px;
        height: root.height - 4px;
        background: white;
        border-radius: 9999px;
        animate x { duration: UAppTheme.animation-duration; }
    }

    clicked => {
        checked = !checked;
    }
    states [
        disabled when !root.enabled: {
            background: checked ? UAppTheme.primary.disabled : UAppTheme.color-fill-secondary;
            circle.background: white.with-alpha(0.8);
        }
        hover when root.has-hover: {
            background: checked ? UAppTheme.primary.hover : UAppTheme.color-fill-plus;
        }
    ]
}
