import { UAppTheme } from "../app-theme.slint";
import { UPrimaryColor } from "../structs/theme.slint";
import { UIcon } from "icon.slint";
import { UText } from "text.slint";
import { IconTextPlacement } from "../structs/data-structs.slint";


export enum UTagVariant {
	filled,
	solid,
	outline,
}

export enum UTagPreset {
	red,
	volcano,
	orange,
	gold,
	yellow,
	lime,
	green,
	cyan,
	blue,
	geekblue,
	purple,
	magenta,
}

export component UTag inherits Rectangle {
	// Accessability properties
	accessible-role: AccessibleRole.text;
    accessible-label: self.text;
	// Regular properties
    in-out property <UTagVariant> variant: filled;
    in-out property <UTagPreset> preset: blue;
    in-out property <UPrimaryColor> preset-color: get-preset-color();
    in-out property <brush> text-color;
    in-out property <string> text;
    in-out property <image> icon;
    in-out property <bool> colorize-icon: true;
    in-out property <IconTextPlacement> icon-placement: hidden;
    border-radius: UAppTheme.radius-base;
    HorizontalLayout {
        spacing: UAppTheme.spacing-small;
        padding-top: UAppTheme.padding-vertical / 1.5;
        padding-bottom: UAppTheme.padding-vertical / 1.5;
        padding-left: UAppTheme.padding-horizontal / 1.5;
        padding-right: UAppTheme.padding-horizontal / 1.5;
        if icon-placement == IconTextPlacement.start: VerticalLayout {
            alignment: center;
            UIcon {
                source: icon;
                size: UAppTheme.font-size-base;
                colorize: colorize-icon ? text-color : transparent;
            }
        }
        VerticalLayout {
            padding-top: 1px;
            padding-bottom: -1px;
            UText {
                text: root.text;
                color: text-color;
                font-size: UAppTheme.font-size-small;
            }
        }

        if icon-placement == IconTextPlacement.end: VerticalLayout {
            alignment: center;
            UIcon {
                source: icon;
                size: UAppTheme.font-size-base;
                colorize: colorize-icon ? text-color : transparent;
            }
        }
    }

    states [
        filled when variant == UTagVariant.filled: {
            background: preset-color.selected;
            text-color: preset-color.hover;
        }
        solid when variant == UTagVariant.solid: {
            background: preset-color.base;
            text-color: UAppTheme.primary-text;
        }
        outline when variant == UTagVariant.outline: {
            background: preset-color.selected;
            text-color: preset-color.hover;
            border-color: preset-color.disabled;
            border-width: 1px;
        }
    ]
    function get-preset-color() -> UPrimaryColor {
        if self.preset == UTagPreset.red {
            return UAppTheme.dust-red;
        } else if self.preset == UTagPreset.volcano {
            return UAppTheme.volcano;
        } else if self.preset == UTagPreset.orange {
            return UAppTheme.sunset-orange;
        } else if self.preset == UTagPreset.gold {
            return UAppTheme.calendula-gold;
        } else if self.preset == UTagPreset.yellow {
            return UAppTheme.sunrise-yellow;
        } else if self.preset == UTagPreset.lime {
            return UAppTheme.lime;
        } else if self.preset == UTagPreset.green {
            return UAppTheme.polar-green;
        } else if self.preset == UTagPreset.cyan {
            return UAppTheme.cyan;
        } else if self.preset == UTagPreset.blue {
            return UAppTheme.daybreak-blue;
        } else if self.preset == UTagPreset.geekblue {
            return UAppTheme.geek-blue;
        } else if self.preset == UTagPreset.purple {
            return UAppTheme.golden-purple;
        } else if self.preset == UTagPreset.magenta {
            return UAppTheme.french-magenta;
        }
        return UAppTheme.primary;
    }
}
